language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: DaUuMhE9JhP2OV5qj9Q1r6dfbXCkm/8QY4EJ+qdlQF0BY8/7TwRB+aGU3zfSgik+Tp7hnsyDEqJG6NYV0B9mqSxazWFAu56XT32lSGFbqXt1ob9M9LVO+wtoV1pnvZojz4T6hJ8/nR9MxL6MN5gHgKUpsXQzYQpuV6cG7pDp5eP3LWkN6hybD56FLeuJv384fTX6elpAXzHDO4hK2FonCU/ZD4KP7H2l65XZkgCE3CYwPG0SIsVxtndVvj4JxVz88KNV2klZtIJjRvHGj3JmM3UMdG8yrBI64c/mBavUgkkY8f5zlSNCfdet2mfZuPdOgpp5DAeZYfUDu2eCD4lcEC0jVgwGOOklBZze177H97cPCdBc6di1s4UlJdlLvgwlEuPBrBQ7SjoAT6tkCU0JAflCTfPLmgfyjs/rgP9fFWaDvLlS2K1gXEW9nV61p59urcHL+5XSDTo8zcmeo+M7xgzWIvdDBBRh51hW/wMF52UQEu83PlF1DrssDLBk+OArZGEeXxrSuBynJcu6NsjhB+6pHucRII3H/fTGEukgeGAu7MvuikWpy4lSkG2S1Ne5IFbM/43wY0AZQPPJJotJ64S09UQ2KEwVOfNNV1Z3B+/+pmTdNOgphN4PNuLi1NQUe/90bpks4/hC8YOpDxhS6N4G0on2SXQzfxHB/vEnNA4=
  - secure: nFBmWGkqNdKnSpcgTQ4naC9ZQtisTkXday0WllxZzfPud01qBer3luIhfyfVweGCYxu+W6v1oM2kRDmMjDjs1kg/lYQZ5vWaS7w2zxiJXVuR+GBk9Innvk6J/ZIDP1nu2PDqzg6N2EoJ91Pw2rqN6zqCn9rsrO6YLbz0Umj07YnsLYw6zjvvmT3jCjIHsY7mWy124lmgV2vxTdpAfvnUc0ZDCpRHUsMc7DfJij6Sk7zQyciINgvBN0DPbrUvqAVJqjS32AKUEGx4PSujaceRiif8jvWLc1rphtTLAs893AoQfocfFdwK+85Eeg/A311UKNoiNkVzG2wD6pnwM8TpgPkJhT312hcv7HKB62gqc2L+L2LmMHWTKCUkJYKHnfP5MuZZoYZFmvgpAkiz2xVuI1k8XcH/efzOtc/WNuNpTnyjMl5OhP/YcpPRTDFw0hOu9Tt00HM6rZk0v7OCUWajKnaaMPyRG9gR7BHjNTCsYXBw0urq14ZmaV7vSulCURKHu8XGpzDg94G2ciGjfc5nARrC2nX1zpdTzCxmx26TWjeFF2CM0SurW63yY2LgglndLSIbhlLIHdtiGK6N+Q0VOp5DswvRlKKBMafz4ftXkuHrjJErW3jWchjTOiiGkJnyvNDPVfyPuIJJGmJWXH7jCM2xaf1Rg1KVksjRaSXbI5w=
