language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: QES3PrdxZDmp9PK3KAx2wU+5k7/vZ1VimIkIYWAqgNxpFxa5wxPZUJkxv9Slu0teKbWoE7xKcBF1N7PSGCgtvUGZPHOgsjPCIA1QutPm+WMFURzdYhA0LModj3EWcWS/q3H4AADwtjSm9YDfwJwarR/yyGkwgBD3GhX0QDr+T+3j0bUZZrd8PFfkikIR1ENbAWm0bpo9YdfMErudLwABMeBm0MifTsuQJnPn+tOsojS4kxiBDexCtF8CrRkRNaA75znF10pS2gKftg58N/XWmiYXSprHam9cjuZoVkiIpI+Ygl6N6vP0IPwbo2FWEKHEyM3VNxh41+zL6Nq53rkCYABYX98zNECMTrvYmNDVzt5NpilEZQl8Hn7CQBDzV7vBdV/Qe68pmWRehhlIA8vMnJLTnAw2NwC8tuXr5oAhC1Nn3ueob1bbNmt3scDYEgdklKAaa9x7ORqc1CRNO4RG1faE/T88ic9rqOgDts2O2/D6lg+EtIaJr4LmbriJGXrjr18+lFO6/VfvCZt1pmVIJtPmLYVqO/LRTUVEyiGM6L9eJIM9Qv8wZlKRajth6Ruu3UKV/plyBCRgR9275SLJlAQJLO6hGxSRI/DOyC+OQCOY7T/SQ/8FXoV/CVzMxGyAjcWKVdxgDtgZztmQ+z3ZoaGdR6ruy/XYe++jk4DLPxE=
  - secure: UOhnxZ929drcM1o2pKg7YxQyUhjvMCtuHfMtvA+Vb1CecOLYTR/L59loiggu2ZWL1o7DWkUX1qeF/MP4XtkI/i09ilATLrlN9ERaGYuXbJqi7KbjSwYqNfdgG5FpIMJxtL4mzEJOCY6KUrRAw36QLXdDgTd+YBF4kDN0P3cgvblEfXhE5C53K5eGOjaJxzAnTEtEj98o1+rOc7K6esN9QirXviEZSZ9ppC9kb7gNjdcHWnYN59ez0zLepsy5VlYGImBI0GmlV2Yuab5NPwXwy1WeXmXU4h4Yrgz81huVBkRSQTBCmb0dnakrPNcEFtWDq8A7fQCTuM4Czcf2yleodymfQiFS+57xThw8rUr42AcdGXAlQxu/JBuiS8d+StJirbVmgYgpekL7YFSL5AZSQ0ms0DHFPBWbm2+HMxhBWtlX+pvOdITEc8AhUYctPznGRiLZspOrbR2v1QM768Z3BB1Fay/9lnQt12LKguki7jfpWmcs4zPYcTuQ+eZlg6ekpCLd9+kaiD2fG82W2R6ZDf+OAhYTnK9hTWW6y2fABiMsSCYEIO5eVAd39u9advtEf2PSB2zougJNFT0s8HQAZ5ceymw3Ov5eV5VvlN9TitMz8nFO5caFQJCRe6BU7ZZxaT1wfGRFvEBApKOFhf5PwaDZ1trw9p78RIYk5SjmKp8=
